# -*- coding: utf-8 -*-
{
    "name": "ARKA-AIM Drone Fixed-Asset Register",
    "version": "19.0.1.0.0",
    "summary": "Per-unit fixed-asset subledger for the AIM drone fleet, reconciled "
    "to the 31-May-2026 opening-balance GL.",
    "description": """
ARKA-AIM Drone Fixed-Asset Register
===================================

Builds the ``custom.fixed.asset`` subledger (register) for PT Aero Inovasi Media
(AIM) from the drone PO (``001/AIM-SES/01/25``, 30-Jan-2025) and the physical
serial listing. One record per unit (~3,329 rows).

The drones are ALREADY carried as a lump sum in the AIM opening-balance GL
(module ``custom_arka_aim_opening_balance``):

* ``1205104000`` Fixed Assets-Cost-Office & outlet equipment : Dr 27,110,131,391
* ``1205203000`` Accum depre-Office & outlet equipment       : Cr  6,776,493,895
* net book value 20,333,637,496

So this module posts **no acquisition journal** -- it only creates the register
records (which touch no GL on create) and seeds one *posted-but-un-GL'd* opening
depreciation line per asset (``posted=True, move_id=False``) that carries each
asset's pro-rata share of the 6,776,493,895 accumulated depreciation. The forward
depreciation schedule (48-month straight line, anchored on the 31-May-2026 opening
date) is then generated by ``action_confirm`` so the monthly cron only ever posts
*future* lines.

Reconciliation (surfaced by ``scripts/tenants/arkaaim/verify_asset_register.py``):

* register cost ties to PO (~27,145,108,236); variance to GL cost = +34,976,845
  (immaterial -- flagged for Finance, GL not touched);
* seeded accumulated depreciation sums to 6,776,493,895;
* register NBV ties to 20,333,637,496.

Idempotent: skips if any AIM ``custom.fixed.asset`` already exists. Company is
resolved by NAME (not hardcoded id), so it is portable across the
trn_arkaaim_begbal / prd_arkaaim databases.

Source data: ``docs/skenario-arka-aim/Listing Asset - odoo.xlsx`` +
``PO Drone 1500unit.pdf``; CSV generated by
``scripts/tenants/arkaaim/build_asset_register.py``.

TENANT-SCOPED: install only on the ARKA-AIM databases.
""",
    "author": "Platform",
    "category": "Tenants/ARKA-AIM",
    "license": "LGPL-3",
    "depends": [
        "custom_accounting_asset",
    ],
    "data": [
        "views/fixed_asset_views.xml",
        "data/seed_functions.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
}
