# -*- coding: utf-8 -*-
"""Happy-path tests for custom.crm.web.form.token."""

from __future__ import annotations

from odoo.exceptions import UserError
from odoo.tests import TransactionCase, tagged


@tagged("post_install", "-at_install")
class TestWebFormToken(TransactionCase):
    def test_token_autogenerated_and_unique(self):
        t1 = self.env["custom.crm.web.form.token"].create({"name": "Landing /demo"})
        t2 = self.env["custom.crm.web.form.token"].create({"name": "Landing /pricing"})
        self.assertTrue(t1.token and t2.token)
        self.assertNotEqual(t1.token, t2.token)

    def test_ingest_payload_creates_lead(self):
        tok = self.env["custom.crm.web.form.token"].create({"name": "Landing /demo"})
        lead_id = self.env["custom.crm.web.form.token"].ingest_payload(
            tok.token,
            {
                "name": "Demo Request from Acme",
                "company": "Acme Co",
                "email": "buyer@acme.test",
                "phone": "+62810000000",
                "message": "We want a demo next week.",
            },
        )
        self.assertTrue(lead_id)
        lead = self.env["crm.lead"].browse(lead_id)
        self.assertEqual(lead.partner_name, "Acme Co")
        self.assertEqual(lead.email_from, "buyer@acme.test")
        tok.invalidate_recordset()
        self.assertEqual(tok.use_count, 1)
        self.assertTrue(tok.captured_at)

    def test_ingest_payload_rejects_unknown_token(self):
        with self.assertRaises(UserError):
            self.env["custom.crm.web.form.token"].ingest_payload(
                "definitely-not-a-real-token",
                {"name": "x"},
            )

    def test_rotate_token_changes_value(self):
        tok = self.env["custom.crm.web.form.token"].create({"name": "Rotate me"})
        original = tok.token
        tok.action_rotate_token()
        self.assertNotEqual(original, tok.token)
