# ============================================================
# Odoo 19 Platform — environment template
# Copy to .env and fill in all REQUIRED values before `make up`.
# Entrypoint will fail-fast on values containing the literal `changeme`.
# ============================================================
# ----- Compose project -----
COMPOSE_PROJECT_NAME: odoo19-platform
# ----- Ports (override jika bentrok dengan service lain di host) -----
ODOO_HTTP_PORT: "18069"
ODOO_LONGPOLL_PORT: "18072"
POSTGRES_PORT: "15432"
REDIS_PORT: "16379"
AI_GATEWAY_PORT: "18080"
PREDICTOR_PORT: "18090"
PROMETHEUS_PORT: "19090"
GRAFANA_PORT: "13000"
LOKI_PORT: "13100"
ALERTMANAGER_PORT: "19093"
PGADMIN_PORT: "15050"
MAILPIT_UI_PORT: "18025"
MAILPIT_SMTP_PORT: "11025"
NGINX_HTTP_PORT: "18000"
NGINX_HTTPS_PORT: "18443"
OLLAMA_PORT: "11434"
# ----- Secrets (WAJIB diganti — entrypoint fail-fast jika ada `changeme`) -----
POSTGRES_USER: odoo
POSTGRES_PASSWORD: ENC[AES256_GCM,data:m9X5HHgo4dLa3ZVL4vo/tQJaXt/CrYs=,iv:iff2ZYn7n8d1UgiXvluMPZNU12BvEthnkmSm4wWerPA=,tag:p0lMtN5CXKMN2YPIW01xSg==,type:str]
POSTGRES_DB: postgres
ODOO_ADMIN_PASSWD: ENC[AES256_GCM,data:pY8jgACvvpokrfJ/WkciP3kLIA==,iv:ZvG2jHTW+Fq8LnKVCmKfg4e5Ho/CAWTWYQYnWTBex2g=,tag:W3uBM0+WnpnyXqWHGTQoQA==,type:str]
REDIS_PASSWORD: ENC[AES256_GCM,data:VoNdO1Iq8x7tyR6YgDfqw8E1f5cGNw==,iv:rWNrr1skhF6ZsBKKbDQFoqJsXSoY8l8SR8cnbF2y3WU=,tag:l1em8JaJIvwbFjXh7TpfXQ==,type:str]
GRAFANA_ADMIN_USER: admin
GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:qRZ4ldG06tRMGydzhoxHQ/4QDOnt,iv:L1wwPgHLStTEl7g7Q5hgnUZ7hA1keBvyz433qGs/tCE=,tag:UA0+oyBoHtzbPNKJ8e8ZRQ==,type:str]
PGADMIN_EMAIL: admin@example.com
PGADMIN_PASSWORD: ENC[AES256_GCM,data:A+XY35oXVGyVm7hZUhT/IA==,iv:zp0jXE3g8GPCDjLvpA33VDE7nf2Qly1InV+mQ9dAp5Q=,tag:jj6hUb0pHu7waF2nxR5Qhw==,type:str]
GATEWAY_SHARED_SECRET: ENC[AES256_GCM,data:1mWWVo9anUmNt7jBHEa+WgObx7R903qrlyhWSLk821Pdeu2CqNXYX6yDISSiRGg666cJZdcDzeeE+TbX66Evhg==,iv:QarmG4cl/v9OzvJ9c6EugWDvHRm3SuD4iJ3DtivHQvc=,tag:0cXOYOAFfIdrtp+n0Rc7UQ==,type:str]
CORETAX_SERTEL_MASTER_KEY: ENC[AES256_GCM,data:PRzvB58io+2cQ0IfYMnK4dTKjdW323Guhi/mTJitGt53uneiFikMZus0DGk=,iv:ZWUd/v8LCY9y8bZjaxDyReEVamS6M99rSrBob7GJEzI=,tag:N/wG4AKd3b0sjXOpg1cHjQ==,type:str]
# ----- AI providers -----
AI_PROVIDER: 'anthropic                          # anthropic | openai | ollama'
AI_MODEL_DEFAULT: claude-sonnet-4-6
AI_MODEL_QUALITY: claude-opus-4-7
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:pS9LGdR496jXQG5CM+7rrp8u1X30Lb28LgsPw0QDvdo8bEYBCHUIdHl00NacyheyQkiQ3hPXRtz/DnsTax2j97vW1dwTY3fRLCUhMA240semU+InBe0HkSql0YfFeo+z1Vx/F8gViQ==,iv:ysG7yhn5u5ORZDP4CT+mpXYPy7Mxtj38YDdsewC8cxw=,tag:HSxrv0hilwpzvBysYBnBTQ==,type:str]
OPENAI_API_KEY: ""
OPENAI_MODEL_DEFAULT: gpt-4o
OLLAMA_BASE_URL: http://ollama:11434
OLLAMA_MODEL_DEFAULT: llama3.2
# ----- Odoo runtime -----
WORKERS: '0                                      # dev=0, prod>=4'
MAX_CRON_THREADS: "2"
LIST_DB: 'true                                   # prod=false'
WITHOUT_DEMO: '                                  # prod=all'
LIMIT_TIME_CPU: "600"
LIMIT_TIME_REAL: "1200"
LIMIT_MEMORY_SOFT: "2147483648"
LIMIT_MEMORY_HARD: "2684354560"
LOG_LEVEL: 'info                                 # debug|info|warn|error|critical'
PROXY_MODE: "True"
DBFILTER: ^.*$
SERVER_WIDE_MODULES: base,web,queue_job
# ----- Network policy -----
EXPOSE_DB: 'false                                # true = postgres listen di host (dev only)'
EXPOSE_REDIS: "false"
# ----- Observability -----
PROMETHEUS_RETENTION: 30d
LOKI_RETENTION: '336h                            # 14 days'
PREDICTOR_INTERVAL_HOURS: "6"
ALERTMANAGER_WEBHOOK_URL: '                      # opsional: Slack/Discord webhook'
ALERTMANAGER_EMAIL_TO: ""
SMTP_HOST: mailpit
SMTP_PORT: "1025"
SMTP_USER: ""
SMTP_PASSWORD: ""
# ----- Predictor / capacity planning -----
HOST_CPU_CORES: "8"
HOST_RAM_GB: "32"
HOST_DISK_GB: "500"
# ----- TLS (prod) -----
TLS_CERT_PATH: ./nginx/certs/server.crt
TLS_KEY_PATH: ENC[AES256_GCM,data:yd8IbfuLxqffJiruGxWrJQ1S41p265Mn,iv:LXjaLc/LhkscLTyuB79gR65eWfVvT2E+jZtZUNBkHfY=,tag:D2QQJ5EglwLdmqxRbafflA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWazdRS2dCbkh5L21wYytJ
            N255eEQxZ3BSVUQ1NG1wNThjR3BzNElBVldVCjJSOCtqS3B0UklwSjZPSGNuaEYv
            eFZ1azdMMFNKRU9na0VaTEZJTHc1djQKLS0tIEs1VUsyem5BYVRtc1RnYmJnMzhj
            MVp6dGZTY1NkRnVkeFRaR2pueXVlcFEKYMULOVSSc5C01UDNQlrw9SzoIuVgmCsT
            NteltH9ygNJKGnay7jYRtV0avP9GFw3Tcp+n5ly03udM4F023IWFyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdh3mpmewqdzp73hr7ypk429n0ut3ex6c9qxlj26u9lfg6vyvp7qj524f4
    encrypted_regex: (?i)(password|passwd|secret|key|token|api[_-]?key|credential|sertel|private|ANTHROPIC_API_KEY|OPENAI_API_KEY|GATEWAY_SHARED_SECRET|CORETAX_SERTEL|S3_(ACCESS|SECRET))
    lastmodified: "2026-05-16T06:13:14Z"
    mac: ENC[AES256_GCM,data:AcI6bBN6VM2/rH6SVjT6aYtZM2dIL9myYj0FKhv3zwZ4Vy4rwpekHii7bFayyy7DDW/qG5GAJRZyj78LIdopqIEtj1qQLcoVdnXvkpJFxZ8i9OxpBWB3ZlX4sKl3Hj7xAT8i556Kwk17r3KuiAqq+94iHIELDkdMt3m6qsTInDM=,iv:rASGm0LMddKgmr70BchXtW2RS4ZE6wzdcmkieOoAIrw=,tag:sNTSHN3jjceQFUEGXdVR1w==,type:str]
    version: 3.13.0
