from . import withholding_category
from . import withholding_rule
from . import account_move_withholding_line
from . import account_tax_inherit
from . import account_move_inherit
from . import res_partner_inherit
from . import res_company_inherit
from . import res_country_inherit
from . import uom_inherit
from . import product_template_inherit
