# -*- coding: utf-8 -*-
{
    "name": "Custom PDP Consent",
    "summary": "Consent management with audited grant/withdraw (UU 27/2022)",
    "description": "Subject consent purposes, recorded consents, expiry & withdrawal.",
    "author": "Custom Platform",
    "website": "https://example.com/custom-platform",
    "category": "Custom Platform/Compliance/PDP",
    "version": "19.0.0.1.0",
    "license": "LGPL-3",
    "depends": ["custom_core", "custom_pdp_core", "custom_pdp_audit", "portal"],
    "capability_tags": ["pdp", "audit-trail", "compliance", "consent"],
    "data": [
        "security/pdp_security.xml",
        "security/ir.model.access.csv",
        "data/pdp_consent_purpose_data.xml",
        "views/pdp_consent_purpose_views.xml",
        "views/pdp_consent_views.xml",
        "views/portal_templates.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
