# -*- coding: utf-8 -*-
import logging

from odoo import _, api, fields, models

_logger = logging.getLogger(__name__)


class MailingMailing(models.Model):
    _inherit = "mailing.mailing"

    x_consent_purpose_id = fields.Many2one(
        "pdp.consent.purpose",
        string="Required Consent Purpose",
        help=(
            "If set, only recipients with an active pdp.consent record under "
            "this purpose will receive the mailing."
        ),
    )
    x_gallery_template_id = fields.Many2one(
        "custom.email.template.gallery",
        string="Template Gallery Source",
    )
    x_uu_pdp_footer = fields.Boolean(
        string="Append UU PDP Footer",
        default=True,
        help=(
            "When enabled, append a dynamically-rendered Indonesian-language "
            "data controller + unsubscribe footer to comply with UU PDP."
        ),
    )
    x_consent_filtered_count = fields.Integer(
        string="Consent-Filtered Recipient Count",
        readonly=True,
        help="Number of recipients excluded by PDP consent filter at last send.",
    )

    # ------------------------------------------------------------------
    # PDP footer
    # ------------------------------------------------------------------

    def _get_pdp_footer_html(self, res_id=None, email_to=None):
        """Render the UU PDP compliance footer for this mailing.

        Pulls data-controller name from the responsible company, DPO contact
        from company.email (fallback), and emits the standard one-click
        unsubscribe URL generated by ``mass_mailing``. If we don't have an
        explicit recipient (res_id + email_to), we fall back to a static
        notice without an embedded link.
        """
        self.ensure_one()
        company = self.user_id.company_id or self.env.company
        controller_name = company.display_name or _("Pengendali Data")
        dpo_field = getattr(company, "x_pdp_dpo_email", False)
        dpo_email = dpo_field or company.email or "dpo@example.id"
        unsubscribe_url = ""
        if res_id and email_to:
            try:
                unsubscribe_url = self._get_unsubscribe_url(email_to, res_id)
            except Exception as exc:  # pragma: no cover — defensive
                _logger.warning(
                    "[custom_email_marketing] mailing %s: failed to build "
                    "unsubscribe URL for %s/%s: %s",
                    self.id, res_id, email_to, exc,
                )
        unsubscribe_html = (
            '<p>Untuk berhenti berlangganan, klik tautan berikut: '
            '<a href="%s">%s</a>.</p>' % (unsubscribe_url, _("Berhenti Berlangganan"))
            if unsubscribe_url
            else '<p>Untuk berhenti berlangganan, gunakan tautan unsubscribe '
                 'di email ini.</p>'
        )
        return (
            '<hr/>'
            '<div style="font-size:11px;color:#666;">'
            '<p><strong>Pemberitahuan UU PDP:</strong> '
            'Anda menerima email ini karena memberikan persetujuan kepada '
            'pengendali data <strong>%(controller)s</strong>. '
            'Anda berhak menarik persetujuan kapan saja.'
            '</p>'
            '%(unsub)s'
            '<p>Pertanyaan terkait data pribadi: hubungi Data Protection '
            'Officer di <a href="mailto:%(dpo)s">%(dpo)s</a>.</p>'
            '</div>'
        ) % {
            "controller": controller_name,
            "dpo": dpo_email,
            "unsub": unsubscribe_html,
        }

    # ------------------------------------------------------------------
    # Consent filter helper
    # ------------------------------------------------------------------

    def _filter_recipients_by_consent(self, res_ids):
        """Return (kept_ids, filtered_count) given x_consent_purpose_id.

        For res.partner-based mailings, looks up consent directly. For other
        models, we resolve the partner via the standard ``partner_id``
        accessor (best-effort) — records without a partner are kept (we
        can't prove non-consent).
        """
        self.ensure_one()
        if not self.x_consent_purpose_id or not res_ids:
            return list(res_ids or []), 0
        purpose_code = self.x_consent_purpose_id.code
        Consent = self.env["pdp.consent"].sudo()
        model = self.mailing_model_real
        kept = []
        filtered = 0
        try:
            records = self.env[model].sudo().browse(list(res_ids)).exists()
        except KeyError:
            _logger.warning(
                "[custom_email_marketing] mailing %s: unknown model %s, "
                "skipping consent filter", self.id, model,
            )
            return list(res_ids), 0
        for rec in records:
            partner = rec if model == "res.partner" else getattr(rec, "partner_id", False)
            if partner and Consent.check_consent(partner, purpose_code):
                kept.append(rec.id)
            else:
                filtered += 1
        return kept, filtered

    # ------------------------------------------------------------------
    # Send override
    # ------------------------------------------------------------------

    def _action_send_mail(self, res_ids=None):
        """Apply PDP consent filter + append UU PDP footer before sending.

        Filtering happens BEFORE the standard ``_action_send_mail`` runs.
        Footer is appended by temporarily rewriting ``body_html`` for the
        duration of the call, then restored.
        """
        for mailing in self:
            effective_res_ids = res_ids
            if mailing.x_consent_purpose_id:
                source_ids = res_ids or mailing._get_remaining_recipients()
                kept, filtered = mailing._filter_recipients_by_consent(source_ids)
                mailing.sudo().write({"x_consent_filtered_count": filtered})
                _logger.info(
                    "[custom_email_marketing] mailing %s: PDP consent filter "
                    "purpose=%s kept=%d filtered=%d",
                    mailing.id, mailing.x_consent_purpose_id.code,
                    len(kept), filtered,
                )
                effective_res_ids = kept
                if not effective_res_ids:
                    _logger.info(
                        "[custom_email_marketing] mailing %s: no recipients "
                        "remain after PDP consent filter; skipping send.",
                        mailing.id,
                    )
                    continue

            original_body = mailing.body_html
            try:
                if mailing.x_uu_pdp_footer and original_body:
                    footer = mailing._get_pdp_footer_html()
                    mailing.body_html = (original_body or "") + footer
                if mailing.x_gallery_template_id:
                    mailing.x_gallery_template_id.sudo().write({
                        "times_used": mailing.x_gallery_template_id.times_used + 1,
                    })
                super(MailingMailing, mailing)._action_send_mail(
                    res_ids=effective_res_ids,
                )
            finally:
                if mailing.x_uu_pdp_footer and original_body is not None:
                    mailing.body_html = original_body
        return True

    # ------------------------------------------------------------------
    # Form button: open apply-template wizard
    # ------------------------------------------------------------------

    def action_open_apply_template_wizard(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Apply Template"),
            "res_model": "custom.email.apply.template.wizard",
            "view_mode": "form",
            "target": "new",
            "context": {"default_mailing_id": self.id},
        }

    # ------------------------------------------------------------------
    # Convenience: invoked by AB-test cron
    # ------------------------------------------------------------------

    @api.model
    def _custom_email_marketing_evaluate_ab_winners(self):
        """Cron entrypoint — delegate to ab.test model."""
        self.env["custom.email.ab.test"].cron_evaluate_winner()
