# -*- coding: utf-8 -*-
{
    "name": "Custom PDP Core",
    "summary": "PDP data classification taxonomy (UU 27/2022)",
    "description": "Classification taxonomy for personal data fields under UU PDP.",
    "author": "Custom Platform",
    "website": "https://example.com/custom-platform",
    "category": "Custom Platform/Compliance/PDP",
    "version": "19.0.0.1.0",
    "license": "LGPL-3",
    "depends": ["custom_core"],
    "capability_tags": ["pdp", "compliance", "data-classification"],
    "data": [
        "security/pdp_security.xml",
        "security/ir.model.access.csv",
        "data/pdp_classification_data.xml",
        "data/pdp_field_seed.xml",
        "views/pdp_classification_views.xml",
        "views/ir_model_fields_views.xml",
        "wizards/pdp_tag_fields_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
