# -*- coding: utf-8 -*-
from . import report_wizard_mixin
from . import general_ledger_wizard
from . import trial_balance_wizard
from . import balance_sheet_wizard
from . import profit_loss_wizard
from . import cash_flow_wizard
from . import aged_receivable_wizard
from . import aged_payable_wizard
from . import partner_ledger_wizard
from . import partner_card_wizard
from . import advance_wizard
from . import sales_wizard
from . import tax_report_wizard
from . import faktur_pajak_wizard
from . import ppn_masukan_import_wizard
from . import bupot_wizard
from . import spt_ppn_wizard
from . import pph_withholding_wizard
from . import nsfp_monitoring_wizard
from . import npwp_quality_wizard
from . import p3p4_wizards
from . import day_book_wizard
from . import purchase_wizard
from . import credit_limit_wizard
from . import gl_open_items_wizard
from . import bill_payment_wizard
from . import sales_detail_wizard
