"""Post-init hook: create missing bank accounts and post the 31-May-2026 opening
balances for the AIM and ARKA companies.

The opening balance is posted as **detail**: one line per source transaction
from the client's "TB & Detail" workbook (``data/opening_detail_*.csv``,
generated by ``tools/parse_arkaaim_begbal_detail.py``), all dated on the
cutover. Per-account totals equal the trial balance exactly; the aggregate
one-line-per-account CSVs it replaced are kept in ``data/`` as an archive.

Data is read directly by this hook (NOT loaded as ORM records), because the
target accounts are resolved by (company, code) at runtime rather than by fixed
external ids -- the two companies use different account namespaces (AIM:
arka_aim.coa_*, ARKA: account.2_erajaya_*) and this keeps the module portable
across the clone/UAT/prod databases.
"""

import csv
import logging
from datetime import date

from odoo.fields import Command
from odoo.exceptions import UserError
from odoo.tools import file_open

_logger = logging.getLogger(__name__)

MODULE = "custom_arka_aim_opening_balance"
OPEN_DATE = date(2026, 5, 31)
REF = "Saldo Awal Detail 31 Mei 2026"
LEGACY_REF = "Saldo Awal 31 Mei 2026"  # the aggregate move this one supersedes

# General journals reserved for Odoo's own machinery -- never post begbal there.
TECHNICAL_JOURNALS = ("EXCH", "CABA", "STJ")
# AIM calls its manual journal MISC, ARKA calls it JM; pick by code rather than
# taking whichever general journal happens to come first (that used to land the
# ARKA opening balance in a purchase journal).
JOURNAL_PREFERENCE = ("MISC", "JM")

# (company display name, opening-balance CSV) -- one posted move per company.
COMPANY_FILES = [
    ("PT Aero Inovasi Media", "data/opening_detail_aim.csv"),
    ("PT Aero Reksa Kreasi Angkasa", "data/opening_detail_arka.csv"),
]

_TRUE = {"1", "true", "yes", "t", "y"}


def _read_csv(relpath):
    with file_open(f"{MODULE}/{relpath}", "r") as fh:
        return list(csv.DictReader(fh))


def _general_journal(env, company):
    """The manual general journal for `company`, never a technical one."""
    Journal = env["account.journal"].with_company(company)
    candidates = Journal.search([("type", "=", "general"), ("company_id", "=", company.id)]).filtered(
        lambda journal: journal.code not in TECHNICAL_JOURNALS
    )
    for code in JOURNAL_PREFERENCE:
        match = candidates.filtered(lambda journal, code=code: journal.code == code)
        if match:
            return match[0]
    return candidates[:1]


def _resolve(env, code, company):
    """Find the single account with this code that belongs to `company`."""
    return (
        env["account.account"]
        .with_company(company)
        .search([("code", "=", code), ("company_ids", "in", company.id)], limit=1)
    )


def _ensure_missing_accounts(env):
    Company = env["res.company"]
    for row in _read_csv("data/missing_accounts.csv"):
        company = Company.search([("name", "=", row["company_name"])], limit=1)
        if not company:
            _logger.warning(
                "opening_balance: company %r not found, skip account %s",
                row["company_name"],
                row["code"],
            )
            continue
        if _resolve(env, row["code"], company):
            continue
        env["account.account"].with_company(company).create(
            {
                "code": row["code"],
                "name": row["name"],
                "account_type": row["account_type"],
                "reconcile": row["reconcile"].strip().lower() in _TRUE,
                "company_ids": [Command.link(company.id)],
            }
        )
        _logger.info(
            "opening_balance: created account %s (%s) for %s",
            row["code"],
            row["account_type"],
            company.name,
        )


def _post_company_opening(env, company, relpath):
    Move = env["account.move"].with_company(company)
    existing = Move.search([("ref", "=", REF), ("company_id", "=", company.id)], limit=1)
    if existing:
        _logger.info(
            "opening_balance: move %r already exists for %s (id=%s, state=%s) -> skip",
            REF,
            company.name,
            existing.id,
            existing.state,
        )
        return

    legacy = Move.search([("ref", "=", LEGACY_REF), ("company_id", "=", company.id)], limit=1)
    if legacy:
        # This database still carries the aggregate opening balance. Swapping it
        # for the detail is a deliberate, backed-up operation -- see
        # scripts/tenants/arkaaim/load_begbal_detail.py -- not something an
        # install hook should do behind the user's back.
        _logger.warning(
            "opening_balance: %s still has the aggregate move %r (id=%s) -> skip; "
            "run scripts/tenants/arkaaim/load_begbal_detail.py to replace it",
            company.name,
            LEGACY_REF,
            legacy.id,
        )
        return

    journal = _general_journal(env, company)
    if not journal:
        raise UserError(f"opening_balance: no general (Miscellaneous) journal for {company.name}")

    lines, unresolved = [], []
    for row in _read_csv(relpath):
        acc = _resolve(env, row["code"], company)
        if not acc:
            unresolved.append(row["code"])
            continue
        # An account.move.line has no date of its own, so the original
        # transaction date, document number and counterparty live in the label.
        label = " | ".join(
            part for part in (row.get("txn_date"), row.get("doc_no"), row.get("notes"), row.get("partner")) if part
        )
        lines.append(
            Command.create(
                {
                    "account_id": acc.id,
                    "name": label[:500] or "Saldo Awal " + row["code"],
                    "debit": float(row["debit"] or 0),
                    "credit": float(row["credit"] or 0),
                }
            )
        )
    if unresolved:
        raise UserError(f"opening_balance: unresolved account codes for {company.name}: {unresolved}")

    move = Move.create(
        {
            "move_type": "entry",
            "journal_id": journal.id,
            "date": OPEN_DATE,
            "ref": REF,
            "line_ids": lines,
        }
    )
    move.action_post()
    total = sum(l[2]["debit"] for l in lines)
    _logger.info(
        "opening_balance: posted %s move id=%s lines=%s total=%.0f",
        company.name,
        move.id,
        len(lines),
        total,
    )


def post_init_hook(env):
    _ensure_missing_accounts(env)
    Company = env["res.company"]
    for company_name, relpath in COMPANY_FILES:
        company = Company.search([("name", "=", company_name)], limit=1)
        if not company:
            _logger.warning("opening_balance: company %r not found, skip opening move", company_name)
            continue
        _post_company_opening(env, company, relpath)
    _logger.info("opening_balance: post_init_hook done")
